### PR TITLE
Define the .well-known response as JSON

### PR DESCRIPTION
**Pull request by pes10k**
change the definition of the returned text from an ordered map to a JSON object, to both have something thats implementable in JSON and maximally compatible

### CODE REVIEW

**Comment by asoltani** [comment]
@pes10k @dharb merging is blocked.  do you want to resubmit?

**Comment by pes10k** [comment]
Sure, i can rebase

**Comment by dharb** [comment]
Merging just requires someone with write access to leave an approving review first. If this proves to be a pain point let me know and we can consider alternatives.

**Comment by asoltani** [comment]
i can give @pes10k admin privs -- or just ping me when you've rebased and I will merge

**Pull request merged**
